version: "3"

services:
  web:
    container_name: molior-web
    build:
      context: .
      dockerfile: docker/dev/web-dev.Dockerfile
    depends_on:
      - molior
    networks:
      - molior
    ports:
      - "8000:4200"
    volumes:
      - ../molior-web2:/app

  molior:
    container_name: molior-server
    build:
      context: .
      dockerfile: docker/dev/molior-dev.Dockerfile
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
      - nginx
      - registry
    networks:
      - molior
    ports:
      - "127.0.0.1:9999:9999"
    volumes:
      - ./:/app
      - pgsock:/var/run/postgresql/
      - /var/run/docker.sock:/var/run/docker.sock
      - molior:/var/lib/molior/

  postgres:
    container_name: molior-postgres
    build:
      context: .
      dockerfile: docker/common/postgres.Dockerfile
    networks:
      - molior
    volumes:
      - pgsock:/var/run/postgresql/
      - postgres:/var/lib/postgresql/15/main

  aptly:
    container_name: molior-aptly
    build:
      context: .
      dockerfile: docker/dev/aptly-dev.Dockerfile
    env_file: .env
    networks:
      - molior
    ports:
      - "127.0.0.1:3142:3142"
    volumes:
      - ../aptly:/app
      - aptly:/var/lib/aptly/

  nginx:
    container_name: molior-nginx
    build:
      context: .
      dockerfile: docker/common/nginx.Dockerfile
    env_file: .env
    depends_on:
      - aptly
    networks:
      - molior
    ports:
      - "8080:8000"
    volumes:
      - aptly:/var/lib/aptly/

  registry:
    container_name: molior-registry
    build:
      context: .
      dockerfile: docker/common/registry.Dockerfile
    env_file: .env
    networks:
      - molior
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - registry:/var/lib/docker-registry/

networks:
  molior:
    name: molior

volumes:
     pgsock:
     postgres:
     registry:
     aptly:
     molior:
