version: "3"

services:
  web:
    container_name: molior-web
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    ports:
      - "8000:4200"
    volumes:
      - ../molior-web2:/app

  api:
    container_name: molior-api
    profiles: ["serve"]
    build:
      context: .
      dockerfile: docker/api.Dockerfile
      args:
          DOCKER_GROUP_ID: ${DOCKER_GROUP_ID}
    ports:
      - "9999:9999"
    volumes:
      - ./:/app
      - pgsock:/var/run/postgresql/
      - /var/run/docker.sock:/var/run/docker.sock
      - molior:/var/lib/molior/

  postgres:
    container_name: molior-postgres
    build:
      context: .
      dockerfile: docker/postgres.Dockerfile
    volumes:
      - pgsock:/var/run/postgresql/
      - postgres:/var/lib/postgresql/15/main

  aptly:
    container_name: molior-aptly
    profiles: ["serve"]
    build:
      context: .
      dockerfile: docker/aptly.Dockerfile
    ports:
      - "3142:3142"
    volumes:
      - ../aptly:/app
      - aptly:/var/lib/aptly/

  nginx:
    container_name: molior-nginx
    profiles: ["serve"]
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    ports:
      - "8080:8000"
    volumes:
      - ../aptly:/app
      - aptly:/var/lib/aptly/

  registry:
    container_name: molior-registry
    profiles: ["serve"]
    build:
      context: .
      dockerfile: docker/registry.Dockerfile
    environment:
      USER: "molior"
      PASSWORD: "molior-registry"
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - registry:/var/lib/docker-registry/

volumes:
     pgsock:
     postgres:
     registry:
     aptly:
     molior:
